export const SYSTEM_CITIES_REQUEST = "SYSTEM_CITIES_REQUEST";
export const SYSTEM_CITIES_FAIL = "SYSTEM_CITIES_FAIL";
export const SYSTEM_CITIES_SUCCESS = "SYSTEM_CITIES_SUCCESS";

export const SYSTEM_AMENITIES_REQUEST = "SYSTEM_AMENITIES_REQUEST";
export const SYSTEM_AMENITIES_FAIL = "SYSTEM_AMENITIES_FAIL";
export const SYSTEM_AMENITIES_SUCCESS = "SYSTEM_AMENITIES_SUCCESS";

export const SYSTEM_REFRESH_REQUEST = "SYSTEM_REFRESH_REQUEST";
export const SYSTEM_REFRESH_FAIL = "SYSTEM_REFRESH_FAIL";
export const SYSTEM_REFRESH_SUCCESS = "SYSTEM_REFRESH_SUCCESS";

export const SYSTEM_APARTMENTS_SUCCESS = "SYSTEM_GET_SUCCESS";
export const SYSTEM_APARTMENTS_FAIL = "SYSTEM_GET_FAIL";
export const SYSTEM_APARTMENTS_REQUEST = "SYSTEM_GET_REQUEST";

export const SYSTEM_MY_GUESTS_SUCCESS = "SYSTEM_MY_GUESTS_SUCCESS";
export const SYSTEM_MY_GUESTS_FAIL = "SYSTEM_MY_GUESTS_FAIL";
export const SYSTEM_MY_GUESTS_REQUEST = "SYSTEM_MY_GUESTS_REQUEST";

export const SYSTEM_BOOKING_APPROVE_SUCCESS = "SYSTEM_BOOKING_APPROVE_SUCCESS";
export const SYSTEM_BOOKING_APPROVE_REQUEST = "SYSTEM_BOOKING_APPROVE_REQUEST";
export const SYSTEM_BOOKING_APPROVE_FAIL = "SYSTEM_BOOKING_APPROVE_FAIL";


export const SYSTEM_BOOKING_REJECT_SUCCESS = "SYSTEM_BOOKING_REJECT_SUCCESS";
export const SYSTEM_BOOKING_REJECT_REQUEST = "SYSTEM_BOOKING_REJECT_REQUEST";
export const SYSTEM_BOOKING_REJECT_FAIL = "SYSTEM_BOOKING_REJECT_FAIL";



export const SYSTEM_MY_BOOKINGS_SUCCESS = "SYSTEM_MY_BOOKINGS_SUCCESS";
export const SYSTEM_MY_BOOKINGS_REQUEST = "SYSTEM_MY_BOOKINGS_REQUEST";
export const SYSTEM_MY_BOOKINGS_FAIL = "SYSTEM_MY_BOOKINGS_FAIL";

 