export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_APARTMENTS_REQUEST = "USER_APARTMENTS_REQUEST";
export const USER_APARTMENTS_SUCCESS = "USER_APARTMENTS_SUCCESS";
export const USER_APARTMENTS_FAIL = "USER_APARTMENTS_FAIL";

export const USER_GET_APARTMENT_REQUEST = "USER_GET_APARTMENT_REQUEST";
export const USER_GET_APARTMENT_SUCCESS = "USER_GET_APARTMENT_SUCCESS";
export const USER_GET_APARTMENT_FAIL = "USER_GET_APARTMENT_FAIL";

export const USER_CREATE_APARTMENTS_REQUEST = "USER_CREATE_APARTMENTS_REQUEST";
export const USER_CREATE_APARTMENTS_SUCCESS = "USER_CREATE_APARTMENTS_SUCCESS";
export const USER_CREATE_APARTMENTS_FAIL = "USER_CREATE_APARTMENTS_FAIL";

export const USER_CREATE_APARTMENTS_RESET = "USER_CREATE_APARTMENTS_RESET";

export const USER_DELETE_APARTMENTS_REQUEST = "USER_DELETE_APARTMENTS_REQUEST";
export const USER_DELETE_APARTMENTS_SUCCESS = "USER_DELETE_APARTMENTS_SUCCESS";
export const USER_DELETE_APARTMENTS_FAIL = "USER_DELETE_APARTMENTS_FAIL";

export const USER_UPDATE_APARTMENTS_REQUEST = "USER_UPDATE_APARTMENTS_REQUEST";
export const USER_UPDATE_APARTMENTS_SUCCESS = "USER_UPDATE_APARTMENTS_SUCCESS";
export const USER_UPDATE_APARTMENTS_FAIL = "USER_UPDATE_APARTMENTS_FAIL";

export const USER_UPDATE_APARTMENTS_RESET = "USER_UPDATE_APARTMENTS_RESET";
